# Generated by Django 4.1.1 on 2022-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_comment_listing_remove_watchlist_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='original_listing', to='auctions.listing'),
        ),
    ]
