# Generated by Django 4.1.1 on 2022-10-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
    ]
