# Generated by Django 4.1.1 on 2022-11-19 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_user_end_date_user_initial_user_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
