# Generated by Django 4.1.1 on 2022-11-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_user_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metric',
            field=models.BooleanField(default=True),
        ),
    ]
